/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#1d1b1a",
        "secondary": "#615e5c",
        "outline-variant": "#e2bebc",
        "primary": "#820012",
        "on-primary-container": "#ffb9b4",
        "secondary-fixed-dim": "#cac5c4",
        "on-surface": "#1b1c19",
        "tertiary-fixed": "#fdddb9",
        "inverse-primary": "#ffb3ae",
        "on-tertiary-fixed": "#281803",
        "surface-container-high": "#eae8e3",
        "on-tertiary-fixed-variant": "#584329",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#910817",
        "on-primary-fixed": "#410004",
        "surface-container-low": "#f5f3ee",
        "error": "#ba1a1a",
        "secondary-container": "#e7e1df",
        "on-secondary-fixed-variant": "#494645",
        "tertiary-fixed-dim": "#e0c29f",
        "surface-dim": "#dbdad5",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "surface-tint": "#b3272c",
        "primary-fixed": "#ffdad7",
        "on-tertiary-container": "#e4c5a2",
        "on-secondary": "#ffffff",
        "tertiary-container": "#675136",
        "surface-variant": "#e4e2dd",
        "on-background": "#1b1c19",
        "inverse-surface": "#30312e",
        "surface-container-highest": "#e4e2dd",
        "surface-container": "#f0eee9",
        "surface": "#fbf9f4",
        "tertiary": "#4e3a21",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-surface-variant": "#5a413f",
        "outline": "#8d706e",
        "on-secondary-container": "#676462",
        "background": "#fbf9f4",
        "primary-container": "#a61d24",
        "primary-fixed-dim": "#ffb3ae",
        "surface-bright": "#fbf9f4",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f2f1ec",
        "secondary-fixed": "#e7e1df",
      },
      fontFamily: {
        headline: ["Newsreader", "serif"],
        body: ["Work Sans", "sans-serif"],
        label: ["Work Sans", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
    },
  },
  plugins: [],
}
